### ISSUE TITLE
Error When Starting (npm run dev)

### ISSUE THREAD

**Issue by afoland** [PrasadBroo/ChatGPT#7]
Running in linux, trying to get this up, errors immediately (complains about "await")

> OS: Linux Mint 21.1 x86_64 
> Kernel: 5.15.0-56-generic 
> Uptime: 18 hours, 36 mins 
> Shell: bash 5.1.16 
> Resolution: 1920x1080 
> DE: Cinnamon 5.6.8 
> Terminal: gnome-terminal 
> CPU: Intel Xeon Gold 6238R (56) @ 4.000GHz 
> GPU: NVIDIA GeForce RTX 3090 
> Memory: 6443MiB / 128194MiB 

~/ChatGPT$ npm run dev

> chatgpt@0.0.0 dev
> vite --host

file:///home/andrew/ChatGPT/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by PrasadBroo** [comment]
make sure you are using nodejs  version >=20.10.0
